### ISSUE TITLE
iOS keyboard (KeyScreen) is hard to hide swipe

### ISSUE THREAD

**Issue by faridfarhan28** [myzinsky/cloudLogOffline#53]
hi, i think about keyboard screen at iOS is little bit hard to hide/unhide swap. Usually it was easy hide just finger swipe to button without press undo or change page. or you can add "Done" button at keyboard so it can easy to hide/unhide. Keyboard

hope you're understand what i mean :)

iOS 15

**Comment by myzinsky** [comment]
In the current iOS I can just drag the screen down and the keyboard removes...
