### ISSUE TITLE
RST and station operator

### ISSUE THREAD

**Issue by Werzi2001** [myzinsky/cloudLogOffline#58]
As 1.1.0 was released in the store I could finally do some testing using my real Cloudlog instance (using station profiles). During that I noticed 2 things that I'm not sure about:

1. RST in the "Add QSO" form is shown as "59" (light grey) by default. I would have expected that I can just leave it that way (without manually tying "59") and having the value "59" being used. But I noticed that during the export to Cloudlog or ADIF the value for RST is just not present (empty). Is it meant to be that way?
2. When I export to Cloudlog the station operator (in Cloudlog "Edit QSO > Station > Operator callsign") is not filled. In the cloudLogOffline settings I have my callsign set and it matches the station profile callsign. Furthermore the <station_callsign:5> is present (and correct) if I export to ADIF. Is this a known issue or is it meant to be that way or is it a problem on the Cloudlog side?

Thanks a lot

**Comment by Werzi2001** [comment]
By the merge requests #63 and #64 this was "fixed".

**Comment by myzinsky** [comment]
TNX
