### ISSUE TITLE
Support for USB/LSB?

### ISSUE THREAD

**Issue by Werzi2001** [myzinsky/cloudLogOffline#68]
I'm just wondering if there is support for submodes USB/LSB at the moment (instead of just SSB)? I found this line of code but I don't see where USB/LSB should be selected as it is not in the modes list:
https://github.com/myzinsky/cloudLogOffline/blob/master/qml/QSOView.qml#L201

**Comment by myzinsky** [comment]
This line is there when FLRIG sends the mode to CloudLogOffline. There were no submodes in cloudlog when I started this app.

**Comment by Werzi2001** [comment]
@myzinsky Ok understood. I'd like to add that. What do you think about a simple solution like adding modes "SSB / LSB" and "SSB / USB" and split it on adif creation into mode and submode? Would that be ok or would you have another solution in mind?

**Comment by myzinsky** [comment]
I think that would be OK if it is ADIF compliant and also is tested with Cloudlog. If you could do this, would be awesome :-)

**Comment by Werzi2001** [comment]
@myzinsky Ok, I'll try to add it. Cloudlog should not be a problem as they already added it. As far as I can tell it is also supported in adif import/export there. And also in the ADIF specification it was added in version 3.0.6 from 2017: https://www.adif.org/306/ADIF_306.htm#Submode_Enumeration

**Comment by Werzi2001** [comment]
Will be solved with #69
