### ISSUE TITLE
Support fields for qo-100

### ISSUE THREAD

**Issue by dennobundy** [myzinsky/cloudLogOffline#70]
i copy here the required fields that are needed to upload to the qo100 DX club log … some are still include :

Your .adi file should contain at least the fields QSO_DATE, TIME_ON, CALL, MODE, BAND that should be "13CM", SAT_NAME that should be "QO-100", and PROP_MODE that should be "SAT".

If present, the field VUCC_GRIDS is parsed according to the ADIF standard (either 2 or 4 grids, separated with ",") and the 4 digit grids listed will be imported in addition to the GRIDSQUARE field.

You can also include your operation grids via the fields MY_GRIDSQUARE and MY_VUCC_GRIDS according to the ADIF standard. If you're operating portable we ask that you upload your logs with this information AND the correct suffix in the callsign.

**Comment by phl0** [comment]
> So essentially we just need additionally:
> 
>     * PROP_MODE
>     * MY_GRIDSQUARE
> 
> @phl0 correct?

Jupp. But PROP_MODE (and SAT_NAME) are already implemented iirc? MY_GRIDSQUARE is nice because it serves for reverse matching the QSOs and for the activated grids map.

**Comment by phl0** [comment]
Why not have both? Set by GPS or by hand alternatively :)
