### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by Werzi2001** [myzinsky/cloudLogOffline#71]
As there were some changes (including mine own) which I'm quite interested in using I was just wondering if there is any kind of regular interval for releases or how it is done.

**Comment by myzinsky** [comment]
Yeah I need some free minutes to test everything and then trigger the release. It might take until end of next week.

**Comment by Werzi2001** [comment]
@myzinsky Don't worry, didn't mean to hurry you. Just wanted to know if it is already planned.
