### ISSUE TITLE
QSO API has changed in Cloudlog 2.0

### ISSUE THREAD

**Issue by garrettben** [myzinsky/cloudLogOffline#79]
The New API requires a station_profile_id field as described in https://github.com/magicbug/Cloudlog/wiki/API. ADIF upload to Cloudlog 2.0 now results in a 500 error because of the missing field.

**Comment by myzinsky** [comment]
Actually it is not required, if it is not set it takes the active station IIRC. Nevertheless, the new version of CLO has an ID field: 

![image](https://user-images.githubusercontent.com/1970554/197326051-d5db3f9f-586e-4507-a548-e87389ce7ef2.png)
