### ISSUE TITLE
API-URL without protocol-prefix

### ISSUE THREAD

**Issue by dg9vh** [myzinsky/cloudLogOffline#8]
Add a filter that throws away the protocol-part of an API-URL (means: throw away http(s)://), because with the protocol identifier, it does not work.

**Comment by myzinsky** [comment]
With let's encrypt its embarrassingly easy to get HTTPs nowadays. However, maybe not everyone is able to manage this. I think I will just change it in a way that ```https://``` or ```http://``` is required.

**Comment by dg9vh** [comment]
... or put both options into a select-box so that one can choose if he wants http - it should default to https meanwhile because this is actually standard.

**Comment by myzinsky** [comment]
Done 6808f5924666a2285f33ce834d63a8d4b51622d7
