### ISSUE TITLE
upload not working in 1.14

### ISSUE THREAD

**Issue by KellyFromSales** [myzinsky/cloudLogOffline#81]
I've not changed any settings from when it was working previously. 

Checked my api key is correct. 
'Test API Key' shows as green when i click it. 

I've tried posting data to my cloudlog instance with postman using my api key and it works as expected. 

I've had a go at monitoring the traffic from the app when i try and upload, to try and rule out a connection being blocked, 
the results from this - testing the api, and then trying to upload - i can see the request to /auth but i don't see one to /qso being made. 

So i'm wondering if the button might not be working for me or something. 

any other steps i can try to debug this? 

android
pixel 7 pro.

**Comment by petrus-lt** [comment]
I have the same issue here. 

with `log_threshold=4` in config.php, I get an error '404 Page Not Found: Indexphp/api' in the cloudlog logs, with an additional 404 in the webserver logs, while as @KellyFromSales I have no issues using curl (200 ok on the same url).

**Comment by KellyFromSales** [comment]
@petrus-lt i think i've tracked down my problem thanks to your comments! 

my local cloudlog instance uses `/Cloudlog/index.php` which i have set up correctly in my app settings. 

however when i try and export in the app to `/api/qso` it's using `cloudlog/index.php/api/qso`  thanks to [this](https://github.com/myzinsky/cloudLogOffline/blob/98902185547b640c33aef90e70611cb00380bb89/src/cloudlogmanager.cpp#L195) `.toLower()` which was added in the last update.

`/cloudlog/index.php/api/qso` doesn't resolve, whereas `Cloudlog/index.php/api/qso` does, so its failing. 
 @myzinsky is it possible to revert this change? or do i need to look at changing my cloudlog instance to use 'cloudlog' ?

**Comment by phl0** [comment]
Made a bugfix on https://github.com/myzinsky/cloudLogOffline/pull/83 and also a fix for autoremoving things like "http://", "https://", trailing "/index.php/api/qso" or trailing slash from URL with https://github.com/myzinsky/cloudLogOffline/pull/84.

**Comment by KellyFromSales** [comment]
appreciate you raising a PR for that so quickly after identifying the issue, thanks!

**Comment by phl0** [comment]
> appreciate you raising a PR for that so quickly after identifying the issue, thanks!

Well it wasn't fast but now it is fixed. Tnx for reporting.

**Comment by KellyFromSales** [comment]
hi @myzinsky 

Do you have any idea when this update will make it out to the store? (or did it go out already and it's not working..)
