### ISSUE TITLE
API sync to Cloudlog instance fails possibly when running in virtual folder on webserver

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r-d-a-t-a** [myzinsky/cloudLogOffline#88]
Steps to reproduce:

1.  Have Cloudlog running in a virtual folder on your webserver (eg https://mydomain.me/cloudlog ) - this can't be that unusual?
2.  Configure cloudLogOffline with read/write API key generated in Cloudlog, and hostname as hostname/cloudlog along with https proto
3.  hit 'Test API Key'

Result:

No output at all, when hitting 'Test API Key', or when attempting to 'export' and 'upload QSOs to Cloudlog' - it silently fails on both.

This behaviour is observed both on Android version 1.1.4 as downloaded from Aurora app store, and when compiled on desktop (version 1.1.5)

**Comment by myzinsky** [comment]
Have you tried "mydomain.me/cloudlog" as url, without "https://" in the string?

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
Yup, tried both. On the desktop version, it actually removes the 'https://' for you, and behaviour is still same.

**Comment by myzinsky** [comment]
@phl0 any ideas?

**Comment by myzinsky** [comment]
Did that resolve?

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
Hi Matthias,

Unfortunately not... If I push the test the API key button nothing happens, equally the Upload to cloudlog button causes nothing to happen.

I have been exporting to adi for now :-)

Thanks,

Andy

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
I am on mobile app 1.1.4 , wondering if there is an update although I don't see one in the store...

**Comment by myzinsky** [comment]
I cannot reproduce your problem. I tried it with my instance it works there. 

1.1.5 is currenlty in preparation for iOS, Android follow later.

**Comment by myzinsky** [comment]
I just installed Cloudlog that way:

<img width="1018" alt="image" src="https://github.com/myzinsky/cloudLogOffline/assets/1970554/c7559457-738e-4144-8835-17ba75f60452">

It just works. So I have no idea, but I think its on your end ... maybe wrong config at your server?

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
I actually worked it out - when you said it could be server config... it's
actually how you enter the config in the app - if you put the trailing
slash on the URL, then you get a 404 in the server logs eg "POST
/cloudlog//index.php/api/qso HTTP/1.1" 404 539 "-" "CloudLogOffline v1.1.4"
- note the two // slashes. Maybe worth validating the input so it cuts off
a trailing slash if it has been entered? Anyway, there it is. Glad I can
now export / upload. Thanks for your help, and the app :)

-----Original Message-----
From: Matthias Jung
Reply-To: myzinsky/cloudLogOffline
To: myzinsky/cloudLogOffline
Cc: c-o-m-m-a-n-d-e-r-d-a-t-a, Author
Subject: Re: [myzinsky/cloudLogOffline] API sync to Cloudlog instance fails
possibly when running in virtual folder on webserver (Issue #88)
Date: 06/01/24 22:47:24

Closed #88 as completed.
