### ISSUE TITLE
Add Info-Buttons in Settings

### ISSUE THREAD

**Issue by dg9vh** [myzinsky/cloudLogOffline#9]
Adding some Info-buttons behind the labels of the settings that are not self-describing.

Button (i) may open a pop-up that contains some helpful text.

Mainly in settings of interest.

**Comment by myzinsky** [comment]
Valid idea, I will tackle this when I create the multi-language option.

**Comment by myzinsky** [comment]
Added here 6808f5924666a2285f33ce834d63a8d4b51622d7
