### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by dg0yt** [myzinsky/cloudLogOffline#95]
Please add tags for the releases since 1.1.0, or at least for the current binary release.

**Comment by dg0yt** [comment]
I have RPM and DEB recipes on build.opensuse.org based on pre-Qt6 state, but this will remain unfinished if versioning remains vague.

**Comment by myzinsky** [comment]
Hi Kai, I have still a bug to solve. If this is done I can create a tag for ne newest release. I will check if I could do an intermediate one :-) e.g. for 1.1.5

**Comment by dg0yt** [comment]
Thanks for 1.1.5. It already uses `QPermission` which needs Qt 6.5.
Either we restore another tag, or we start adding changes which enable using older version of Qt with new versions of cloudlogoffline. If there is an interest in Linux packages in addition to mobile apps.

**Comment by dg0yt** [comment]
The 1.1.4 tag works with Qt 5.15:
https://build.opensuse.org/package/show/home:dg0yt:branches:home:dg0yt/cloudlogoffline
